/**
 * lib/copy-engine/buildPrompt.ts
 *
 * Builds the system prompt and per-step user prompts sent to Claude.
 * Each step has a different angle — initial intro, two follow-ups, graceful exit.
 *
 * ABSOLUTE RULES (baked into system prompt):
 *  1. Never "Partnership opportunity"
 *  2. Never "I wanted to reach out"
 *  3. Always sender's actual name in sign-off
 *  4. Follow-ups must add new value
 *  5. Never mention Aurora or AI
 *  6. UK English throughout
 */

import type { CopyContext } from "./buildContext";

// ─── System prompt ────────────────────────────────────────────────────────────

export function buildSystemPrompt(): string {
  return `You are the Copy Engine for Aurora — an AI outreach assistant for independent creative professionals in the UK.

Your job is to write cold outreach emails that:
- Feel genuinely personal and human — like the sender wrote them at their desk, not like a tool generated them
- Reference specific, real details about the venue — never generic filler
- Are concise and respectful of the recipient's time
- Have one clear, low-friction ask — not "let's partner" but "would you be open to a quick chat"
- Sound like a talented, confident professional — not desperate

ABSOLUTE RULES — NEVER VIOLATE THESE:
1. Never use "partnership opportunity" in the subject or body — ever
2. Never use "I wanted to reach out" as an opener — ever
3. Never sign off as "there" or leave the name blank — always use the sender's actual name
4. Never write a follow-up that just says "following up" with no new value — each follow-up must add something genuine
5. Never use "I came across your venue" — too generic
6. Never mention Aurora, AI, or that the email was generated by software
7. Never exceed 120 words for the initial email
8. Never exceed 100 words for follow-ups
9. Never make promises about results or guarantees
10. Never use exclamation marks — they read as desperate

TONE GUIDE:
- professional: warm but businesslike, clear and direct
- friendly: conversational, approachable, slightly informal
- premium: confident, elegant, implies scarcity of availability
- casual: relaxed, short sentences, feels almost like a text

UK ENGLISH ALWAYS:
- "colour" not "color", "organise" not "organize"
- Drop the Oxford comma in most cases
- Avoid Americanisms like "reaching out", "touch base", "circle back"`;
}

// ─── Initial email prompt ─────────────────────────────────────────────────────

export function buildInitialEmailPrompt(ctx: CopyContext): string {
  const greeting = ctx.recipient.contact_name
    ? `Hi ${ctx.recipient.contact_name},`
    : "Hi there,";

  const specialityLine =
    ctx.sender.speciality_tags.length > 0
      ? ctx.sender.speciality_tags.join(", ")
      : ctx.sender.profession;

  const pastClientsLine =
    ctx.sender.past_clients.length > 0
      ? `I've previously worked with ${ctx.sender.past_clients.slice(0, 2).join(" and ")}.`
      : "";

  const keyPhrase = ctx.recipient.key_phrases[0] ?? null;
  const angle     = ctx.recipient.recommended_angle ?? null;

  const culturalNote =
    ctx.recipient.cultural_relevance > 60
      ? "- HIGH cultural relevance — this venue is likely a fit for Black/African/diaspora weddings. Weight this in the email if it feels natural and genuine."
      : "";

  return `Write a cold outreach email from a photographer to a venue.

SENDER:
- Name: ${ctx.sender.name}
- Profession: ${ctx.sender.profession}
- Speciality: ${specialityLine}
- Positioning: ${ctx.sender.positioning}
- Location: ${ctx.sender.location ?? "UK"}
- Pitch: "${ctx.sender.pitch || "Professional photographer specialising in weddings and events"}"
- Past clients: ${ctx.sender.past_clients.join(", ") || "None listed yet"}
- Tone preference: ${ctx.sender.tone}
- Portfolio: ${ctx.sender.portfolio_url ?? ctx.sender.website ?? "Not provided"}

RECIPIENT VENUE:
- Name: ${ctx.recipient.venue_name}
- Location: ${ctx.recipient.address ?? "Not specified"}
- Google rating: ${ctx.recipient.rating != null ? `${ctx.recipient.rating}/5 (${ctx.recipient.review_count} reviews)` : "Not available"}
- Venue vibe: ${ctx.recipient.venue_vibe ?? "Not analysed yet"}
- Google summary: ${ctx.recipient.google_summary ?? "None"}
${keyPhrase ? `- Specific detail to reference: "${keyPhrase}"` : ""}
${angle ? `- Recommended opening angle: ${angle}` : ""}
${culturalNote}

INSTRUCTIONS:
- Start with: ${greeting}
- Open with something specific about ${ctx.recipient.venue_name} — use the recommended angle or specific detail above
- In 2-3 sentences: who the sender is, their speciality, why this venue specifically
${pastClientsLine ? `- Naturally work in: "${pastClientsLine}"` : ""}
- One soft ask: "Would you be open to a quick chat?" or similar — never pushy
- Sign off with the sender's ACTUAL name: ${ctx.sender.name}
- Maximum 120 words
- UK English throughout
- No exclamation marks

Return ONLY valid JSON — no markdown fences, no preamble, no extra text:
{
  "subject": "<specific, curiosity-driven subject line, 6 words max, never 'partnership'>",
  "subject_alternatives": ["<option 2>", "<option 3>"],
  "body": "<the full email body including greeting and sign-off>",
  "word_count": <integer>,
  "personalisation_score": <0-100 integer — how specific this is to this venue vs a generic venue>
}`;
}

// ─── Follow-up prompt ─────────────────────────────────────────────────────────

export function buildFollowUpPrompt(
  ctx:            CopyContext,
  followUpNumber: number,
  previousEmails: Array<{ subject: string; body: string }>
): string {
  const angles = [
    // Follow-up 1 — add a new angle, reference their work
    `Add a new angle not mentioned in the first email. Could reference a specific service, a relevant recent project, or a genuine question about their upcoming events. Keep it light — this is a gentle nudge, not pressure.`,
    // Follow-up 2 — social proof or useful insight
    `Lead with a brief piece of social proof or a genuinely useful insight. Something like: "I recently shot a ${ctx.recipient.venue_vibe ?? "wedding"} at a similar venue and the couple said it was the best decision they made for their day." Make it feel like you're sharing something valuable, not chasing a response.`,
    // Follow-up 3 — graceful exit
    `This is the final email. Be gracious and leave the door wide open. Acknowledge they're busy. Give them an easy out. Something like: "If the timing isn't right, no worries at all — I'll leave it here but would love to connect when the time is better." No guilt, no pressure. Leave them with a positive impression of the sender.`,
  ];

  const angle           = angles[Math.min(followUpNumber - 1, 2)];
  const previousSubject = previousEmails[0]?.subject ?? `Photography for ${ctx.recipient.venue_name}`;

  return `Write follow-up email #${followUpNumber} in an outreach sequence from ${ctx.sender.name} to ${ctx.recipient.venue_name}.

PREVIOUS EMAILS SENT:
${previousEmails
  .map((e, i) => `Email ${i + 1}:\nSubject: ${e.subject}\n${e.body}`)
  .join("\n\n---\n\n")}

FOLLOW-UP ANGLE FOR THIS EMAIL:
${angle}

SENDER: ${ctx.sender.name}, ${ctx.sender.profession}, specialising in ${ctx.sender.speciality_tags.join(", ") || ctx.sender.profession}
TONE: ${ctx.sender.tone}
VENUE: ${ctx.recipient.venue_name}${ctx.recipient.address ? `, ${ctx.recipient.address}` : ""}

INSTRUCTIONS:
- Subject: "Re: ${previousSubject}" (reply in thread)
- Do NOT start with "just following up on my previous email" — add genuine new value
- Maximum 100 words
- UK English, no exclamation marks
- End with sender's actual name: ${ctx.sender.name}

Return ONLY valid JSON — no markdown, no preamble:
{
  "subject": "Re: ${previousSubject}",
  "body": "<the follow-up body including greeting and sign-off>",
  "word_count": <integer>,
  "new_value_added": "<one sentence — what genuine new value does this email add>"
}`;
}
