/**
 * lib/copy-engine/buildPrompt.ts
 *
 * Builds the system prompt and per-step user prompts sent to Claude.
 * Each step has a different angle — initial intro, two follow-ups, graceful exit.
 *
 * ABSOLUTE RULES (baked into system prompt):
 *  1. Never "Partnership opportunity"
 *  2. Never "I wanted to reach out"
 *  3. Always sender's actual name in sign-off
 *  4. Follow-ups must add new value
 *  5. Never mention Kammie or AI
 *  6. UK English throughout
 */

import type { CopyContext } from "./buildContext";

// ─── System prompt ────────────────────────────────────────────────────────────

export function buildSystemPrompt(ctx: CopyContext): string {
  const pitchContextLine = ctx.sender.pitch_context
    ? `\n\nCONTEXT ABOUT THE SENDER'S GOALS:\n${ctx.sender.pitch_context}`
    : "";

  const locationLine = ctx.sender.location ? ` based in ${ctx.sender.location}` : "";

  return `You are writing outreach emails for a ${ctx.sender.profession} named ${ctx.sender.name}${locationLine}.${pitchContextLine}

Your job is to write cold outreach emails that:
- Feel genuinely personal and human — like the sender wrote them at their desk, not like a tool generated them
- Reference specific, real details about the recipient — never generic filler
- Are concise and respectful of the recipient's time
- Have one clear, low-friction ask — not "let's partner" but "would you be open to a quick chat"
- Sound like a talented, confident professional — not desperate

ABSOLUTE RULES — NEVER VIOLATE THESE:
1. Never use "partnership opportunity" in the subject or body — ever
2. Never use "I wanted to reach out" as an opener — ever
3. Never sign off as "there" or leave the name blank — always use the sender's actual name
4. Never write a follow-up that just says "following up" with no new value — each follow-up must add something genuine
5. Never use "I came across your venue" — too generic
6. Never mention Kammie, AI, or that the email was generated by software
7. Never exceed 120 words for the initial email
8. Never exceed 100 words for follow-ups
9. Never make promises about results or guarantees
10. Never use exclamation marks — they read as desperate

TONE GUIDE:
- professional: warm but businesslike, clear and direct
- friendly: conversational, approachable, slightly informal
- premium: confident, elegant, implies scarcity of availability
- casual: relaxed, short sentences, feels almost like a text

UK ENGLISH ALWAYS:
- "colour" not "color", "organise" not "organize"
- Drop the Oxford comma in most cases
- Avoid Americanisms like "reaching out", "touch base", "circle back"`;
}

// ─── Initial email prompt ─────────────────────────────────────────────────────

export function buildInitialEmailPrompt(ctx: CopyContext): string {
  const isApollo     = ctx.source === "apollo";
  const contactName  = ctx.recipient.contact_name;
  const contactTitle = ctx.recipient.contact_title ?? null;

  // For Apollo records address the individual by first name.
  // For venue records, use full contact name if known, or "there".
  const firstName = contactName ? contactName.split(" ")[0] : null;
  const greeting  = isApollo && firstName
    ? `Hi ${firstName},`
    : contactName
      ? `Hi ${contactName},`
      : "Hi there,";

  const specialityLine =
    ctx.sender.speciality_tags.length > 0
      ? ctx.sender.speciality_tags.join(", ")
      : ctx.sender.profession;

  const pastClientsLine =
    ctx.sender.past_clients.length > 0
      ? `I've previously worked with ${ctx.sender.past_clients.slice(0, 2).join(" and ")}.`
      : "";

  const keyPhrase = ctx.recipient.key_phrases[0] ?? null;
  const angle     = ctx.recipient.recommended_angle ?? null;
  const caution   = ctx.recipient.caution_note ?? null;

  const culturalNote =
    ctx.recipient.cultural_relevance > 60
      ? "- HIGH cultural relevance — this venue is likely a fit for Black/African/diaspora weddings. Weight this in the email if it feels natural and genuine."
      : "";

  const voiceLine = ctx.sender.voice_sample
    ? `- Writing voice examples (MATCH this tone, vocabulary, sentence length and formality level — the output must feel like the same person wrote it):\n  """\n  ${ctx.sender.voice_sample}\n  """`
    : null;

  // Score tier gives the model a calibration signal
  const scoreTier =
    ctx.signal_score >= 70 ? "strong fit"
    : ctx.signal_score >= 40 ? "moderate fit"
    : "speculative lead";

  // Apollo-specific contact reference line
  const apolloContactLine = isApollo && firstName && contactTitle
    ? `- Contact: ${firstName} ${contactName!.split(" ").slice(1).join(" ")} — ${contactTitle} at ${ctx.recipient.venue_name}`
    : isApollo && firstName
      ? `- Contact: ${contactName} at ${ctx.recipient.venue_name}`
      : "";

  // Apollo vs venue opening hook instruction
  const openingInstruction = isApollo && firstName
    ? `- FIRST sentence: lead with the suggested angle — reference ${firstName}'s role${contactTitle ? ` (${contactTitle})` : ""} at ${ctx.recipient.venue_name} naturally. Do NOT open with "I came across your profile" or "I wanted to reach out"`
    : `- FIRST sentence after the greeting: lead with the suggested angle above — do NOT open with a generic "I wanted to reach out" or "I came across your venue"\n- The hook must feel like the sender noticed something genuine and specific about ${ctx.recipient.venue_name}`;

  // For Apollo: sign off with first name only (addressing an individual feels more personal)
  // For venue/manual: sign off with full name as before
  const signOff = isApollo && firstName
    ? ctx.sender.first_name
    : ctx.sender.name;

  return `Write a personalised outreach email${isApollo && firstName && contactTitle
    ? ` to ${contactName}, ${contactTitle} at ${ctx.recipient.venue_name}`
    : isApollo && firstName
      ? ` to ${contactName} at ${ctx.recipient.venue_name}`
      : ` to ${ctx.recipient.venue_name}`}.

SENDER PROFILE:
- Name: ${ctx.sender.name}
- Profession: ${ctx.sender.profession}
- Specialities: ${specialityLine}
- Positioning: ${ctx.sender.positioning}
- Location: ${ctx.sender.location ?? "UK"}
- About them (write in THIS voice — match the tone, vocabulary and energy of this text):
  "${ctx.sender.pitch || `Professional ${ctx.sender.profession} specialising in ${specialityLine}`}"
${voiceLine ? voiceLine : ""}- Past clients: ${ctx.sender.past_clients.join(", ") || "None listed yet"}
- Tone preference: ${ctx.sender.tone}
- Portfolio: ${ctx.sender.portfolio_url ?? ctx.sender.website ?? "Not provided"}

LEAD INTELLIGENCE:
${apolloContactLine ? apolloContactLine + "\n" : ""}- Company/venue name: ${ctx.recipient.venue_name}
- Location: ${ctx.recipient.address ?? "Not specified"}
- Kammie Score: ${ctx.signal_score}/100 (${scoreTier})
${!isApollo ? `- Google rating: ${ctx.recipient.rating != null ? `${ctx.recipient.rating}/5 (${ctx.recipient.review_count} reviews)` : "Not available"}
- Venue vibe: ${ctx.recipient.venue_vibe ?? "Not analysed yet"}
- Google summary: ${ctx.recipient.google_summary ?? "None"}` : ""}
${keyPhrase ? `- Specific detail to reference: "${keyPhrase}"` : ""}
${angle ? `- Suggested angle (USE THIS AS THE OPENING HOOK — the first sentence after the greeting must be built around this): ${angle}` : ""}
${caution ? `- Caution note: ${caution} — be mindful of this; do not reference it directly but let it quietly inform your framing` : ""}
${culturalNote}

INSTRUCTIONS:
- Start with: ${greeting}
${openingInstruction}
${isApollo && firstName
  ? `- Reference ${firstName}'s specific role (${contactTitle ?? "their position"}) in the opening line — make them feel this email was written for them, not a template
- In 2-3 sentences: briefly introduce who the sender is, their specialities (${specialityLine}), and why ${ctx.recipient.venue_name} specifically is interesting to them`
  : `- In 2-3 sentences: who the sender is, their specialities (${specialityLine}), and why this venue specifically suits their work`}
- The voice must match the "About them" text above — not a sales template, not corporate-speak
${pastClientsLine ? `- Naturally work in: "${pastClientsLine}"` : ""}
- One soft ask: "Would you be open to a quick chat?" or similar — never pushy, never "partnership opportunity"
- Never use the word "partnership" anywhere in the email
- Sign off with: ${signOff}${isApollo && firstName ? " (first name only — this is a personal email to an individual)" : ""}
- Maximum 120 words
- UK English throughout
- No exclamation marks

Return ONLY valid JSON — no markdown fences, no preamble, no extra text:
{
  "subject": "<specific, curiosity-driven subject line, 6 words max, never 'partnership'>",
  "subject_alternatives": ["<option 2>", "<option 3>"],
  "body": "<the full email body including greeting and sign-off>",
  "word_count": <integer>,
  "personalisation_score": <0-100 integer — how specific this is to this contact/venue vs a generic template>
}`;
}

// ─── Follow-up prompt ─────────────────────────────────────────────────────────

export function buildFollowUpPrompt(
  ctx:            CopyContext,
  followUpNumber: number,
  previousEmails: Array<{ subject: string; body: string }>
): string {
  const angles = [
    // Follow-up 1 — add a new angle, reference their work
    `Add a new angle not mentioned in the first email. Could reference a specific service, a relevant recent project, or a genuine question about their upcoming events. Keep it light — this is a gentle nudge, not pressure.`,
    // Follow-up 2 — social proof or useful insight
    `Lead with a brief piece of social proof or a genuinely useful insight. Something like: "I recently shot a ${ctx.recipient.venue_vibe ?? "wedding"} at a similar venue and the couple said it was the best decision they made for their day." Make it feel like you're sharing something valuable, not chasing a response.`,
    // Follow-up 3 — graceful exit
    `This is the final email. Be gracious and leave the door wide open. Acknowledge they're busy. Give them an easy out. Something like: "If the timing isn't right, no worries at all — I'll leave it here but would love to connect when the time is better." No guilt, no pressure. Leave them with a positive impression of the sender.`,
  ];

  const angle           = angles[Math.min(followUpNumber - 1, 2)];
  const previousSubject = previousEmails[0]?.subject ?? `Photography for ${ctx.recipient.venue_name}`;

  const isApolloFollowUp = ctx.source === "apollo";
  const followUpFirstName = ctx.recipient.contact_name
    ? ctx.recipient.contact_name.split(" ")[0]
    : null;
  const followUpTarget = isApolloFollowUp && followUpFirstName
    ? `${followUpFirstName} at ${ctx.recipient.venue_name}`
    : ctx.recipient.venue_name;

  // Follow-ups also sign off with first name only for Apollo
  const followUpSignOff = isApolloFollowUp && followUpFirstName
    ? ctx.sender.first_name
    : ctx.sender.name;

  return `Write follow-up email #${followUpNumber} in an outreach sequence from ${ctx.sender.name} to ${followUpTarget}.

PREVIOUS EMAILS SENT:
${previousEmails
  .map((e, i) => `Email ${i + 1}:\nSubject: ${e.subject}\n${e.body}`)
  .join("\n\n---\n\n")}

FOLLOW-UP ANGLE FOR THIS EMAIL:
${angle}

SENDER: ${ctx.sender.name}, ${ctx.sender.profession}, specialising in ${ctx.sender.speciality_tags.join(", ") || ctx.sender.profession}
TONE: ${ctx.sender.tone}
${ctx.sender.voice_sample ? `WRITING VOICE (match this style):\n"""\n${ctx.sender.voice_sample}\n"""\n` : ""}RECIPIENT: ${ctx.recipient.venue_name}${ctx.recipient.address ? `, ${ctx.recipient.address}` : ""}${isApolloFollowUp && followUpFirstName ? `\nCONTACT: ${followUpFirstName}${ctx.recipient.contact_title ? ` (${ctx.recipient.contact_title})` : ""}` : ""}

INSTRUCTIONS:
- Subject: "Re: ${previousSubject}" (reply in thread)
- Greeting: Hi ${isApolloFollowUp && followUpFirstName ? followUpFirstName : (ctx.recipient.contact_name ?? "there")},
- Do NOT start with "just following up on my previous email" — add genuine new value
- Maximum 100 words
- UK English, no exclamation marks
- End with sender's name: ${followUpSignOff}${isApolloFollowUp && followUpFirstName ? " (first name only)" : ""}

Return ONLY valid JSON — no markdown, no preamble:
{
  "subject": "Re: ${previousSubject}",
  "body": "<the follow-up body including greeting and sign-off>",
  "word_count": <integer>,
  "new_value_added": "<one sentence — what genuine new value does this email add>"
}`;
}
